### ISSUE TITLE
About Resnet50_Final.pth

### ISSUE THREAD

**Issue by willwamy** [CatoGit/Comparing-the-Performance-of-Deepfake-Detection-Methods-on-Benchmark-Datasets#1]
When I detect a single deepfake video, the following error occurred. FileNotFoundError: [Errno 2] No such file or directory: 'D:\\pycharmprojects\\methods/deepfake_detector/facedetector/retinaface/Resnet50_Final.pth'
So where is the 'Resnet50_Final.pth'?
THANK U!!!

**Comment by nizarhaider** [comment]
Same problem here. Were you able to fix it?

**Comment by CatoGit** [comment]
The training section of the [Retinaface](https://github.com/biubug6/Pytorch_Retinaface) repository links to a google drive folder with the Resnet50_Final.pth file.
